window.ZUZI_TOURS = [
  {
    id: "luxor",
    name: "Luxor",
    region: "Upper Egypt · Nile",
    icon: "ri-ancient-gate-line",
    tagline: "The world's greatest open-air museum",
    image: "assets/images/gallery/luxor/1.jpeg",
    rating: 4.9,
    reviews: 1284,
    duration: "Full day · ~12 hrs",
    durationShort: "12 hours",
    bestFor: "History & archaeology",
    cardDesc:
      "Walk among the colossal columns of Karnak and descend into the royal tombs of the Valley of the Kings on the East and West Banks.",
    longDesc:
      "Once the mighty capital of ancient Thebes, Luxor holds an unmatched concentration of monuments. Our full-day tour crosses both banks of the Nile — from the towering hypostyle hall of Karnak to the painted tombs hidden deep in the Valley of the Kings. A licensed Egyptologist guide brings every hieroglyph to life, while comfortable transport and a riverside lunch keep the day effortless.",
    highlights: [
      { icon: "ri-ancient-gate-line", title: "Karnak Temple Complex" },
      { icon: "ri-building-2-line", title: "Luxor Temple by night" },
      { icon: "ri-treasure-map-line", title: "Valley of the Kings" },
      { icon: "ri-flower-line", title: "Temple of Hatshepsut" },
      { icon: "ri-statue-line", title: "Colossi of Memnon" },
      { icon: "ri-ship-line", title: "Nile felucca sail" },
    ],
    gallery: [
      { src: "assets/images/gallery/luxor/1.jpeg"},
      { src: "assets/images/gallery/luxor/2.jpeg"},
      { src: "assets/images/gallery/luxor/3.jpeg"},
      { src: "assets/images/gallery/luxor/4.jpeg"},
      { src: "assets/images/gallery/luxor/5.jpeg"},
      { src: "assets/images/gallery/luxor/6.jpeg"},
      { src: "assets/images/gallery/luxor/7.jpeg"},
    ],
    itinerary: [
      { time: "05:30", title: "Pick-up & departure", text: "Air-conditioned transfer from your hotel, with breakfast on the go." },
      { time: "09:00", title: "Karnak Temple", text: "Explore the largest religious complex ever built with your guide." },
      { time: "12:00", title: "Lunch on the Nile", text: "Local restaurant overlooking the river (included)." },
      { time: "13:30", title: "Valley of the Kings", text: "Visit three royal tombs in the Valley, incl. Hatshepsut Temple." },
      { time: "17:00", title: "Colossi of Memnon", text: "Photo stop at the giant statues of Amenhotep III." },
      { time: "19:30", title: "Return", text: "Drop-off back at your hotel." },
    ],
    included: ["Licensed Egyptologist guide", "All entrance fees", "Lunch at a Nile-side restaurant", "Hotel pick-up & drop-off", "Air-conditioned transport", "Bottled water"],
    excluded: ["Tips & gratuities", "Tutankhamun's tomb (optional extra)", "Personal expenses"],
  },

  {
    id: "luxor-balloon",
    name: "Luxor Hot Air Balloon",
    region: "Upper Egypt · Luxor",
    icon: "ri-windy-line",
    tagline: "Sunrise over the world's greatest open-air museum",
    image: "assets/images/luxor-balloon.png",
    rating: 4.9,
    reviews: 1740,
    duration: "Morning · ~2 hrs",
    durationShort: "2 hours",
    bestFor: "Unforgettable views",
    cardDesc:
      "Glide above Luxor at sunrise in a hot air balloon, watching the Nile, the Valley of the Kings and ancient temples unfold beneath you.",
    longDesc:
      "There is no view in Egypt quite like the one from a hot air balloon at dawn over Luxor. Long before the crowds arrive, you rise into a sky full of colour as the sun spills gold across the Nile, the green farmland of the West Bank and the desert mountains beyond. From your basket you can trace the full sweep of ancient Thebes — the Valley of the Kings, the Temple of Hatshepsut, the Colossi of Memnon and the Ramesseum — all laid out like a map below you. The flight lasts roughly 45 minutes and is operated by fully licensed pilots with an impeccable safety record, making it a serene, once-in-a-lifetime experience for couples, families and first-time flyers alike.",
    highlights: [
      { icon: "ri-sun-line", title: "Sunrise over the Nile" },
      { icon: "ri-windy-line", title: "45-minute balloon flight" },
      { icon: "ri-treasure-map-line", title: "Valley of the Kings from above" },
      { icon: "ri-flower-line", title: "Temple of Hatshepsut aerial view" },
      { icon: "ri-medal-2-line", title: "Licensed pilots & safety record" },
      { icon: "ri-camera-3-line", title: "Unbeatable photo opportunities" },
    ],
    gallery: [
      { src: "assets/images/gallery/luxor-balloon/1.jpeg", caption: "In the basket with the pilot at dawn" },
      { src: "assets/images/gallery/luxor-balloon/2.jpeg", caption: "A fleet of balloons over the West Bank" },
      { src: "assets/images/gallery/luxor-balloon/3.png", caption: "Floating above the temples of Luxor" },
      { src: "assets/images/gallery/luxor-balloon/4.jpg", caption: "Colourful balloons over the desert" },
    ],
    itinerary: [
      { time: "04:00", title: "Early pick-up", text: "Transfer from your Luxor hotel to the West Bank launch site." },
      { time: "04:45", title: "Safety briefing", text: "Meet your pilot, tea & coffee, and a full safety briefing." },
      { time: "05:15", title: "Lift-off", text: "The balloon rises as the sun begins to break over the Nile." },
      { time: "05:30", title: "The flight", text: "A 45-minute glide over the Valley of the Kings and temples." },
      { time: "06:15", title: "Landing & certificate", text: "Gentle landing and a commemorative flight certificate." },
      { time: "07:00", title: "Return", text: "Transfer back to your hotel in time for breakfast." },
    ],
    included: ["45-minute balloon flight", "Licensed pilot & crew", "Safety briefing", "Tea, coffee & snacks", "Commemorative flight certificate", "Hotel pick-up & drop-off"],
    excluded: ["Tips & gratuities", "Photos & souvenirs", "Personal expenses"],
  },

  {
    id: "aswan",
    name: "Aswan",
    region: "Upper Egypt · Nubia",
    icon: "ri-ship-line",
    tagline: "Where the Nile is at its most beautiful",
    image: "assets/images/aswan.jpg",
    rating: 4.8,
    reviews: 642,
    duration: "Full day · ~10 hrs",
    durationShort: "10 hours",
    bestFor: "Culture & relaxation",
    cardDesc:
      "Sail to the temple island of Philae, stand beneath the mighty High Dam and glide over the Nile on a traditional felucca.",
    longDesc:
      "Aswan is calmer and greener than anywhere else on the Nile — a sun-drenched Nubian city of islands, granite boulders and sailboats. This tour pairs the iconic Philae Temple (rescued from the rising waters) with the engineering marvel of the High Dam, the ancient Unfinished Obelisk and a peaceful felucca cruise around Elephantine and the Botanical Garden.",
    highlights: [
      { icon: "ri-flower-line", title: "Philae Temple (Isis)" },
      { icon: "ri-building-line", title: "Aswan High Dam" },
      { icon: "ri-tools-line", title: "The Unfinished Obelisk" },
      { icon: "ri-leaf-line", title: "Botanical Garden island" },
      { icon: "ri-ship-line", title: "Traditional felucca sail" },
      { icon: "ri-store-2-line", title: "Nubian village visit" },
    ],
    gallery: [
      { src: "assets/images/gallery/aswan/1.jpeg"},
      { src: "assets/images/gallery/aswan/2.jpeg"},
      { src: "assets/images/gallery/aswan/3.jpeg"},
      { src: "assets/images/gallery/aswan/4.jpeg"},
      { src: "assets/images/gallery/aswan/5.jpeg"},
      { src: "assets/images/gallery/aswan/6.jpeg"},
      { src: "assets/images/gallery/aswan/7.jpeg"},
    ],

    itinerary: [
      { time: "07:00", title: "Pick-up", text: "Meet your guide and head to the first site." },
      { time: "08:30", title: "Philae Temple", text: "Motorboat ride to the island temple of Isis." },
      { time: "11:00", title: "High Dam & Obelisk", text: "Visit the dam and the ancient granite quarries." },
      { time: "13:00", title: "Lunch", text: "Nubian-style lunch by the river (included)." },
      { time: "14:30", title: "Felucca cruise", text: "Relaxing sail past Elephantine & the Botanical Garden." },
      { time: "17:00", title: "Return", text: "Transfer back to your accommodation." },
    ],
    included: ["Licensed Egyptologist guide", "Entrance fees", "Motorboat to Philae", "Felucca cruise", "Lunch", "Hotel transfers", "Bottled water"],
    excluded: ["Tips & gratuities", "Optional Nubian village dinner", "Personal expenses"],
  },

  {
    id: "abu-simbel",
    name: "Abu Simbel",
    region: "Upper Egypt · Lake Nasser",
    icon: "ri-statue-line",
    tagline: "The twin temples of Ramses the Great",
    image: "assets/images/abu-simbel.jpg",
    rating: 4.9,
    reviews: 511,
    duration: "Full day · ~9 hrs",
    durationShort: "9 hours",
    bestFor: "Bucket-list monuments",
    cardDesc:
      "Stand before the four colossal statues of Ramses II and the temple of Queen Nefertari, saved stone-by-stone from the rising Nile.",
    longDesc:
      "Carved directly into the mountainside in the 13th century BC, the temples of Abu Simbel are among Egypt's most breathtaking sights — and a UNESCO World Heritage marvel. Relocated in a heroic rescue operation in the 1960s, they now rise above the waters of Lake Nasser. Your guide reveals the solar alignment, the battle reliefs and the love story behind the smaller temple dedicated to Nefertari.",
    highlights: [
      { icon: "ri-statue-line", title: "Four Colossi of Ramses II" },
      { icon: "ri-sun-line", title: "Solar alignment phenomenon" },
      { icon: "ri-heart-3-line", title: "Temple of Nefertari" },
      { icon: "ri-water-flash-line", title: "Lake Nasser views" },
      { icon: "ri-shield-star-line", title: "UNESCO rescue story" },
      { icon: "ri-ancient-pavilion-line", title: "Battle of Kadesh reliefs" },
    ],
    gallery: [
      { src: "assets/images/gallery/abu-simbel/1.jpg"},
      { src: "assets/images/gallery/abu-simbel/3.jpeg"},
      { src: "assets/images/gallery/abu-simbel/4.jpeg"},
    ],
    itinerary: [
      { time: "04:30", title: "Early departure", text: "Road transfer across the desert (convoy safety) — or optional flight." },
      { time: "08:00", title: "Great Temple", text: "Guided tour of the temple of Ramses II." },
      { time: "10:00", title: "Temple of Nefertari", text: "Visit the smaller temple dedicated to Hathor & the Queen." },
      { time: "11:30", title: "Lake Nasser & free time", text: "Photo stops and the visitor centre rescue exhibit." },
      { time: "13:00", title: "Lunch", text: "Lunch in Abu Simbel (included)." },
      { time: "14:30", title: "Return", text: "Transfer back to Aswan / hotel." },
    ],
    included: ["Licensed Egyptologist guide", "Entrance fees", "Road transport in convoy", "Lunch", "Hotel pick-up & drop-off", "Bottled water"],
    excluded: ["Tips & gratuities", "Optional return flight", "Sound & light show (optional)", "Personal expenses"],
  },

  {
    id: "giza",
    name: "Giza Pyramids",
    region: "Greater Cairo",
    icon: "ri-ancient-pyramid-line",
    tagline: "The last surviving wonder of the ancient world",
    image: "assets/images/giza.jpg",
    rating: 5.0,
    reviews: 2317,
    duration: "Half day · ~5 hrs",
    durationShort: "5 hours",
    bestFor: "First-time visitors",
    cardDesc:
      "Meet the Great Pyramid of Khufu, ride between the pyramids and unlock the mystery of the Great Sphinx on the Giza Plateau.",
    longDesc:
      "No trip to Egypt is complete without standing at the foot of the Great Pyramids of Giza — the only Ancient Wonder still standing. This half-day experience covers the full plateau: the Great Pyramid of Khufu, the pyramids of Khafre and Menkaure, a panoramic viewpoint perfect for photos, and the enigmatic Great Sphinx with its valley temple. Optional add-ons let you step inside a pyramid or visit the Grand Egyptian Museum.",
    highlights: [
      { icon: "ri-ancient-pyramid-line", title: "Great Pyramid of Khufu" },
      { icon: "ri-camera-3-line", title: "Panoramic photo point" },
      { icon: "ri-emotion-line", title: "The Great Sphinx" },
      { icon: "ri-museum-line", title: "Valley Temple" },
      { icon: "ri-horse-line", title: "Optional camel ride" },
      { icon: "ri-building-4-line", title: "Grand Egyptian Museum add-on" },
    ],

    gallery: [
      { src: "assets/images/gallery/giza/1.jpeg"},
      { src: "assets/images/gallery/giza/2.jpeg"},
      { src: "assets/images/gallery/giza/3.jpeg"},
      { src: "assets/images/gallery/giza/4.jpeg"},
      { src: "assets/images/gallery/giza/5.jpeg"},
      { src: "assets/images/gallery/giza/6.jpeg"},
      { src: "assets/images/gallery/giza/7.jpeg"},
      { src: "assets/images/gallery/giza/8.jpeg"},
      { src: "assets/images/gallery/giza/9.jpeg"},
    ],
    itinerary: [
      { time: "08:00", title: "Pick-up", text: "Transfer from your Cairo/Giza hotel." },
      { time: "09:00", title: "Great Pyramid", text: "Walk the plateau and learn about Khufu's masterpiece." },
      { time: "11:00", title: "Panoramic view", text: "Best photo spot of all three pyramids together." },
      { time: "12:00", title: "Great Sphinx", text: "Visit the Sphinx and its valley temple." },
      { time: "13:00", title: "Return", text: "Drop-off, or add the Grand Egyptian Museum." },
    ],
    included: ["Licensed Egyptologist guide", "Plateau entrance fees", "Hotel pick-up & drop-off", "Air-conditioned transport", "Bottled water"],
    excluded: ["Inside-pyramid ticket (optional)", "Camel ride (optional)", "Grand Egyptian Museum (optional)", "Tips & gratuities", "Lunch"],
  },

  {
    id: "marsa-alam",
    name: "Marsa Alam",
    region: "Red Sea · Egypt",
    icon: "ri-ship-2-line",
    tagline: "Pristine reefs, dolphins and desert nights",
    image: "assets/images/marsa-alam.jpeg",
    rating: 4.8,
    reviews: 876,
    duration: "Full day · ~8 hrs",
    durationShort: "8 hours",
    bestFor: "Snorkelling & diving",
    cardDesc:
      "Swim with spinner dolphins at the famous Dolphin House, snorkel virgin reefs and end the day with a Bedouin dinner under the stars.",
    longDesc:
      "Marsa Alam is the Red Sea at its most unspoiled — warm turquoise water, vibrant house reefs and the legendary Sataya Dolphin House. Our day blends a boat trip to snorkel and dive among friendly spinner dolphins with the option of a quad-bike desert safari and a traditional Bedouin dinner beneath a sky full of stars. Perfect for couples, families and ocean lovers of every level.",
    highlights: [
      { icon: "ri-emotion-happy-line", title: "Dolphin House (Sataya)" },
      { icon: "ri-water-flash-line", title: "Pristine coral reefs" },
      { icon: "ri-bubble-chart-line", title: "Snorkel & dive stops" },
      { icon: "ri-restaurant-line", title: "Bedouin dinner" },
      { icon: "ri-roadster-line", title: "Quad-bike desert safari" },
      { icon: "ri-star-smile-line", title: "Stargazing in the dunes" },
    ],
    gallery: [
      { src: "assets/images/gallery/marsa-alam/3.jpeg"},
      { src: "assets/images/gallery/marsa-alam/4.jpeg"},
      { src: "assets/images/gallery/marsa-alam/5.jpeg"},
      { src: "assets/images/gallery/marsa-alam/6.jpeg"},
      { src: "assets/images/gallery/marsa-alam/7.jpeg"},
      { src: "assets/images/gallery/marsa-alam/8.jpeg"},
      { src: "assets/images/gallery/marsa-alam/9.jpeg"},
    ],
    itinerary: [
      { time: "08:00", title: "Boat departure", text: "Board at the marina and cruise toward Sataya Reef." },
      { time: "10:00", title: "Dolphin House", text: "Snorkel alongside wild spinner dolphins (2 stops)." },
      { time: "13:00", title: "Onboard lunch", text: "Fresh lunch served on the boat (included)." },
      { time: "15:00", title: "Third reef stop", text: "One more snorkel/dive over the coral gardens." },
      { time: "17:00", title: "Desert option", text: "Optional quad safari, camel ride & Bedouin dinner." },
      { time: "20:30", title: "Return", text: "Transfer back to your hotel." },
    ],
    included: ["Boat trip & crew", "Snorkelling equipment", "Two guided reef stops", "Onboard lunch & drinks", "Hotel transfers", "Guide"],
    excluded: ["Diving (optional extra)", "Quad-bike safari (optional)", "Bedouin dinner (optional)", "Tips & gratuities"],
  },

  {
    id: "marsa-mubarak",
    name: "Marsa Mubarak",
    region: "Red Sea · Marsa Alam",
    icon: "ri-leaf-line",
    tagline: "Crystal-clear waters and lush marine gardens",
    image: "assets/images/marsa-mubarak.webp",
    rating: 4.8,
    reviews: 412,
    duration: "Half day · ~4 hrs",
    durationShort: "4 hours",
    bestFor: "Snorkelling & diving",
    cardDesc:
      "Discover crystal-clear waters and expansive seagrass meadows 60 km from Marsa Alam — a beloved marine park especially popular with divers from around the world.",
    longDesc:
      "Marsa Mubarak is a protected bay of astonishingly clear water that lies about 60 kilometres from the city of Marsa Alam. Its shallow marine park shelters one of the Red Sea's largest beds of seagrass, drawing grazing sea turtles and gentle dugongs into the warm shallows. Long a favourite destination — and warmly embraced by Russian visitors — it offers effortless shore snorkelling over gardens of coral and marine plants found in few other places. Whether you glide across the reef or simply float above the meadows, Marsa Mubarak is a serene window into Red Sea marine life.",
    highlights: [
      { icon: "ri-water-flash-line", title: "Crystal-clear sheltered bay" },
      { icon: "ri-leaf-line", title: "Vast seagrass meadows" },
      { icon: "ri-emotion-happy-line", title: "Sea turtle sightings" },
      { icon: "ri-bubble-chart-line", title: "Coral gardens snorkelling" },
      { icon: "ri-anchor-line", title: "Shore-entry diving" },
      { icon: "ri-shield-star-line", title: "Protected marine park" },
    ],

    gallery: [
      { src: "assets/images/gallery/marsa-mubarak/1.jpeg"},
      { src: "assets/images/gallery/marsa-mubarak/2.jpeg"},
      { src: "assets/images/gallery/marsa-mubarak/3.jpeg"},
      { src: "assets/images/gallery/marsa-mubarak/4.jpeg"},
      { src: "assets/images/gallery/marsa-mubarak/5.jpeg"},
      { src: "assets/images/gallery/marsa-mubarak/6.jpeg"},
      { src: "assets/images/gallery/marsa-mubarak/7.jpeg"},
    ],

    itinerary: [
      { time: "08:00", title: "Pick-up", text: "Transfer from your Marsa Alam hotel to the bay." },
      { time: "09:00", title: "Snorkel briefing", text: "Kit-up and short briefing with your guide." },
      { time: "09:30", title: "Seagrass meadows", text: "Snorkel over the meadows in search of turtles and dugongs." },
      { time: "11:00", title: "Coral gardens", text: "Second swim along the reef and coral gardens." },
      { time: "12:00", title: "Beach break", text: "Relax on the shore with refreshments (included)." },
      { time: "13:00", title: "Return", text: "Transfer back to your hotel." },
    ],
    included: ["Snorkelling equipment", "Guided reef swim", "Two snorkel stops", "Refreshments", "Hotel pick-up & drop-off", "Guide"],
    excluded: ["Diving (optional extra)", "Tips & gratuities", "Personal expenses"],
  },

  {
    id: "submarine",
    name: "Submarine Adventure",
    region: "Red Sea · Marsa Alam & Hurghada",
    icon: "ri-ship-2-line",
    tagline: "Dive beneath the surface without getting wet",
    image: "assets/images/submarine.jpg",
    rating: 4.7,
    reviews: 689,
    duration: "Half day · ~3 hrs",
    durationShort: "3 hours",
    bestFor: "Families & non-swimmers",
    cardDesc:
      "Descend below the Red Sea's surface in a real submarine, exploring deep coral gardens and marine life through panoramic windows — no swimming required.",
    longDesc:
      "Your adventure begins in Marsa Alam or Hurghada. A submarine is a specialised marine vessel capable of diving below the water's surface, navigating to great depths, and surfacing again. It operates on Archimedes' principle, controlling its weight and density to dive and ascend — the very technology once used for military purposes, scientific research and exploration. Today it lets every traveller, swimmers and non-swimmers alike, drift past vivid coral gardens, shoals of tropical fish and the silent beauty of the deep — all in complete comfort behind panoramic windows. A perfect family experience that brings the underwater world within everyone's reach.",
    highlights: [
      { icon: "ri-ship-2-line", title: "Real submarine descent" },
      { icon: "ri-camera-lens-line", title: "Panoramic underwater windows" },
      { icon: "ri-water-flash-line", title: "Coral gardens at depth" },
      { icon: "ri-bubble-chart-line", title: "Tropical fish shoals" },
      { icon: "ri-user-smile-line", title: "Perfect for non-swimmers" },
      { icon: "ri-parent-line", title: "Family-friendly" },
    ],

    gallery: [
      { src: "assets/images/gallery/submarine/1.jpeg"},
      { src: "assets/images/gallery/submarine/2.jpeg"},
      { src: "assets/images/gallery/submarine/3.jpeg"},
      { src: "assets/images/gallery/submarine/4.jpeg"},
      { src: "assets/images/gallery/submarine/5.jpeg"},
      { src: "assets/images/gallery/submarine/6.jpeg"},
    ],

    itinerary: [
      { time: "08:30", title: "Pick-up", text: "Transfer from your hotel to the marina in Marsa Alam or Hurghada." },
      { time: "09:30", title: "Boarding", text: "Board the submarine and safety briefing." },
      { time: "10:00", title: "The descent", text: "Dive below the surface to the coral gardens." },
      { time: "10:45", title: "Deep reef", text: "Glide past corals and fish at depth through panoramic windows." },
      { time: "11:30", title: "Surfacing", text: "Return to the surface and the marina." },
      { time: "12:30", title: "Return", text: "Transfer back to your hotel." },
    ],
    included: ["Submarine excursion", "Safety briefing", "Hotel pick-up & drop-off", "Guide", "Air-conditioned transport", "Bottled water"],
    excluded: ["Tips & gratuities", "Photos & souvenirs", "Personal expenses"],
  },

  {
    id: "sharm-el-luli",
    name: "Sharm El Luli Beach",
    region: "Red Sea · Wadi El Gemal",
    icon: "ri-sun-line",
    tagline: "Ranked among the world's top 25 beaches",
    image: "assets/images/sharm-el-luli.jpg",
    rating: 4.9,
    reviews: 547,
    duration: "Full day · ~7 hrs",
    durationShort: "7 hours",
    bestFor: "Beach & relaxation",
    cardDesc:
      "Unwind on Hankorab beach, 60 km south of Marsa Alam inside the Wadi El Gemal reserve — ranked among the world's top 25 beaches and first in the Middle East.",
    longDesc:
      "If you are in Marsa Alam and want to relax away from your hotel, Sharm El Luli Beach — also known as Hankorab — is the perfect escape. It lies 60 kilometres south of Marsa Alam in the Red Sea Governorate, within the protected Wadi El Gemal area. In 2018 it was ranked among the top 25 beaches in the world and first in the Middle East, and it remains one of the most sought-after destinations for international visitors. A pristine arc of white sand meets a shallow, turquoise lagoon fringed by an untouched house reef, making it ideal for swimming, snorkelling and simply soaking in the serenity of one of Egypt's most beautiful coastlines.",
    highlights: [
      { icon: "ri-medal-line", title: "Top-25 world beach (2018)" },
      { icon: "ri-shield-star-line", title: "Wadi El Gemal protected area" },
      { icon: "ri-sun-line", title: "Pristine white sand" },
      { icon: "ri-water-flash-line", title: "Turquoise lagoon" },
      { icon: "ri-bubble-chart-line", title: "Untouched house reef" },
      { icon: "ri-restaurant-line", title: "Snorkelling & swimming" },
    ],
    gallery: [
      { src: "assets/images/gallery/sharm-el-luli/1.jpeg"},
      { src: "assets/images/gallery/sharm-el-luli/2.jpeg"},
      { src: "assets/images/gallery/sharm-el-luli/3.jpeg"},
      { src: "assets/images/gallery/sharm-el-luli/4.jpeg"},
      { src: "assets/images/gallery/sharm-el-luli/5.jpeg"},
      { src: "assets/images/gallery/sharm-el-luli/6.jpeg"},
      { src: "assets/images/gallery/sharm-el-luli/7.jpeg"},

    ],
    itinerary: [
      { time: "08:00", title: "Pick-up", text: "Transfer from your Marsa Alam hotel to Wadi El Gemal." },
      { time: "09:30", title: "Arrival at the beach", text: "Settle in on the sand and enjoy the lagoon." },
      { time: "10:30", title: "Snorkelling", text: "Guided snorkel over the untouched house reef." },
      { time: "13:00", title: "Lunch", text: "Lunch by the beach (included)." },
      { time: "14:30", title: "Free time", text: "Swim, sunbathe or explore the bay." },
      { time: "16:00", title: "Return", text: "Transfer back to your hotel." },
    ],
    included: ["Transport to Wadi El Gemal", "Snorkelling equipment", "Guided reef snorkel", "Lunch", "Hotel pick-up & drop-off", "Guide"],
    excluded: ["Wadi El Gemal park fee", "Tips & gratuities", "Personal expenses"],
  },

  {
    id: "orange-island",
    name: "Hurghada Speed Trip",
    region: "Red Sea · Hurghada",
    icon: "ri-speed-line",
    tagline: "Dolphins, Orange Island and a fast-boat adventure",
    image: "assets/images/gallery/orange-island/1.jpeg",
    rating: 4.7,
    reviews: 933,
    duration: "Half day · ~4 hrs",
    durationShort: "4 hours",
    bestFor: "Families & snorkelling",
    cardDesc:
      "A thrilling 4-hour speed trip from Hurghada: two hours snorkelling with dolphins, two hours on Orange Island, plus fruit, drinks and hotel transfers.",
    longDesc:
      "Your adventure from Hurghada with the most wonderful speed trips is a packed four-hour escape on the Red Sea. The journey splits into two unforgettable parts: two hours of snorkelling with wild dolphins, watching them leap and play in their natural home, and two hours relaxing on the white sands and clear lagoons of Orange Island (Giftun). Fresh fruit and drinks are provided on board, and round-trip transport to and from your hotel is included. Any food or drink you choose on Orange Island itself is at your own expense. Don't miss this trip — it is the perfect short adventure for families, couples and anyone short on time.",
    highlights: [
      { icon: "ri-speed-line", title: "4-hour speed-boat trip" },
      { icon: "ri-emotion-happy-line", title: "2 hours snorkelling with dolphins" },
      { icon: "ri-island-line", title: "2 hours on Orange Island" },
      { icon: "ri-restaurant-line", title: "Fresh fruit & drinks" },
      { icon: "ri-car-line", title: "Hotel transfers included" },
      { icon: "ri-parent-line", title: "Family-friendly pace" },
    ],
    gallery: [
      { src: "assets/images/gallery/orange-island/1.jpeg"},
      { src: "assets/images/gallery/orange-island/2.jpeg"},
      { src: "assets/images/gallery/orange-island/3.jpeg"},
      { src: "assets/images/gallery/orange-island/4.jpeg"},

    ],
    itinerary: [
      { time: "08:30", title: "Pick-up & departure", text: "Hotel transfer and speed-boat departure from the marina." },
      { time: "09:30", title: "Dolphin snorkelling", text: "Two hours snorkelling with wild dolphins." },
      { time: "11:30", title: "Orange Island", text: "Two hours on the island's beach and lagoon." },
      { time: "12:30", title: "Fruit & drinks", text: "Fresh fruit and drinks served on board." },
      { time: "13:00", title: "Return cruise", text: "Cruise back to the marina." },
      { time: "13:30", title: "Return", text: "Transfer back to your hotel." },
    ],
    included: ["Speed-boat trip", "Snorkelling equipment", "Dolphin-watching stop", "Orange Island visit", "Fresh fruit & drinks", "Hotel pick-up & drop-off"],
    excluded: ["Food and drink on Orange Island (own expense)", "Tips & gratuities", "Personal expenses"],
  },


  {
    id: "abu-dabbab",
    name: "Abu Dabbab Beach",
    region: "Red Sea · Marsa Alam",
    icon: "ri-sun-line",
    tagline: "A tranquil bay of sea turtles and gentle dugongs",
    image: "assets/images/abu-dabbab.jpg",
    rating: 4.8,
    reviews: 498,
    duration: "Half day · ~4 hrs",
    durationShort: "4 hours",
    bestFor: "Beach & snorkelling",
    cardDesc:
      "Relax on one of Marsa Alam's most beautiful beaches, 30 km north of the city — clear waters, sandy shores and a famous resident population of sea turtles and dugongs.",
    longDesc:
      "Abu Dabbab Beach is one of the most beautiful and tranquil beaches in Marsa Alam. Located about 30 kilometres north of the city, it is famous for its crystal-clear waters and golden sandy shores. The sheltered bay is home to a beloved population of green sea turtles and the elusive, gentle dugong — often called the sea cow — which grazes on the lush seagrass meadows in the shallows. Like other beaches in the Marsa Alam area, it is also used as a naval base, which has helped keep the surrounding waters pristine and protected. Whether you come to snorkel alongside turtles, spot a dugong, or simply unwind on the soft sand, Abu Dabbab is a perfect half-day escape into unspoiled Red Sea beauty.",
    highlights: [
      { icon: "ri-water-flash-line", title: "Crystal-clear sheltered bay" },
      { icon: "ri-leaf-line", title: "Seagrass meadows" },
      { icon: "ri-emotion-happy-line", title: "Sea turtle encounters" },
      { icon: "ri-bubble-chart-line", title: "Possible dugong sightings" },
      { icon: "ri-sun-line", title: "Golden sandy beach" },
      { icon: "ri-shield-star-line", title: "Protected pristine waters" },
    ],
    gallery: [
      { src: "assets/images/gallery/abu-dabbab/1.jpeg"},
      { src: "assets/images/gallery/abu-dabbab/2.jpeg"},
      { src: "assets/images/gallery/abu-dabbab/3.jpeg"},
      { src: "assets/images/gallery/abu-dabbab/4.jpeg"},

      
    ],
    itinerary: [
      { time: "08:00", title: "Pick-up", text: "Transfer from your Marsa Alam hotel to Abu Dabbab beach." },
      { time: "08:45", title: "Arrival & briefing", text: "Settle in, kit-up and a short snorkel briefing with your guide." },
      { time: "09:15", title: "Snorkelling", text: "Swim over the seagrass meadows in search of turtles and dugongs." },
      { time: "11:00", title: "Beach free time", text: "Relax on the sand, swim or enjoy refreshments." },
      { time: "12:00", title: "Second snorkel", text: "One more swim over the reef before heading back." },
      { time: "13:00", title: "Return", text: "Transfer back to your hotel." },
    ],
    included: ["Snorkelling equipment", "Guided reef swim", "Two snorkel stops", "Refreshments", "Hotel pick-up & drop-off", "Guide"],
    excluded: ["Tips & gratuities", "Personal expenses"],
  },

  {
    id: "marsa-safari",
    name: "Marsa Alam Desert Safari",
    region: "Red Sea · Marsa Alam",
    icon: "ri-roadster-line",
    tagline: "Quad bikes, Bedouin traditions and desert sunsets",
    image: "assets/images/gallery/marsa-safari/2.jpeg",
    rating: 4.7,
    reviews: 731,
    duration: "Half day · ~5 hrs",
    durationShort: "5 hours",
    bestFor: "Adventure & culture",
    cardDesc:
      "A special desert safari: quad bike to a Bedouin tent, ride camels, watch the sunset, browse the market, meet the goats, enjoy a dance show and a fire performance — round-trip transfers included.",
    longDesc:
      "This is a special safari trip from Marsa Alam. We pick you up from your hotel and take you into the mountains of the Eastern Desert. The adventure begins with an exhilarating quad bike ride across the dunes to a traditional Bedouin tent, where you will enjoy a photo session, join the camels for a ride, and watch the sun set over the desert mountains. Inside the tent you can visit a small Bedouin market, take photos with the goats, watch a traditional dance performance, and be amazed by a fire-breathing show. Round-trip transportation from your hotel is included. If you are in Marsa Alam and want to go anywhere, book now — this is the perfect way to experience the desert side of the Red Sea.",
    highlights: [
      { icon: "ri-roadster-line", title: "Quad bike ride across the dunes" },
      { icon: "ri-store-2-line", title: "Bedouin tent & market" },
      { icon: "ri-horse-line", title: "Camel ride" },
      { icon: "ri-sun-line", title: "Desert sunset" },
      { icon: "ri-fire-line", title: "Fire-breathing show" },
      { icon: "ri-music-2-line", title: "Traditional dance performance" },
    ],
    gallery: [
      { src: "assets/images/gallery/marsa-safari/1.jpeg"},
      { src: "assets/images/gallery/marsa-safari/2.jpeg"},
      { src: "assets/images/gallery/marsa-safari/3.jpeg"},

    ],
    itinerary: [
      { time: "13:00", title: "Pick-up", text: "Transfer from your hotel to the quad base in the mountains." },
      { time: "14:00", title: "Quad bike ride", text: "Ride across the dunes to the Bedouin tent." },
      { time: "15:30", title: "Bedouin tent", text: "Camel ride, photo session and browse the Bedouin market." },
      { time: "17:00", title: "Sunset", text: "Watch the sun set over the desert mountains." },
      { time: "17:30", title: "Show & dinner", text: "Traditional dance performance, fire-breathing show and photos with goats." },
      { time: "19:00", title: "Return", text: "Transfer back to your hotel." },
    ],
    included: ["Quad bike ride", "Camel ride", "Bedouin tent visit", "Dance & fire show", "Round-trip hotel transfers", "Guide"],
    excluded: ["Tips & gratuities", "Drinks at the camp", "Personal expenses"],
  },

  {
    id: "dendera-abydos",
    name: "Dendera & Abydos Temples",
    region: "Upper Egypt · Qena & Sohag",
    icon: "ri-ancient-gate-line",
    tagline: "Two of Egypt's most exquisitely decorated temples",
    image: "assets/images/gallery/dendera-abydos/5.jpeg",
    rating: 4.9,
    reviews: 384,
    duration: "Full day · ~12 hrs",
    durationShort: "12 hours",
    bestFor: "History & archaeology",
    cardDesc:
      "From Marsa Alam or Hurghada, journey to the breathtaking Temple of Hathor at Dendera and the sacred Temple of Osiris at Abydos — with guide, lunch and transport included.",
    longDesc:
      "Experience the wonders and beauty of Egypt with us on this full-day journey from Marsa Alam or Hurghada to two of the country's most remarkable temples. The first stop is the Temple of Hathor at Dendera in Qena — famed for its astonishingly preserved, brightly painted ceiling, the famous zodiac relief, and its towering columns crowned with the face of the goddess. The journey continues to the Temple of Osiris at Abydos in Sohag — one of Egypt's most sacred sites, renowned for its exquisitely detailed reliefs depicting the mysteries of the afterlife and the List of Kings. The trip includes lunch, drinks, a licensed tour guide and air-conditioned transport throughout. These two temples offer some of the finest and best-preserved art in all of ancient Egypt.",
    highlights: [
      { icon: "ri-ancient-gate-line", title: "Temple of Hathor, Dendera" },
      { icon: "ri-camera-lens-line", title: "Famous Dendera Zodiac relief" },
      { icon: "ri-building-2-line", title: "Temple of Osiris, Abydos" },
      { icon: "ri-treasure-map-line", title: "The List of Kings at Abydos" },
      { icon: "ri-palette-line", title: "Brilliantly preserved colours" },
      { icon: "ri-sun-line", title: "Painted astronomical ceiling" },
    ],
    gallery: [
      { src: "assets/images/gallery/dendera-abydos/1.jpeg"},
      { src: "assets/images/gallery/dendera-abydos/2.jpeg"},
      { src: "assets/images/gallery/dendera-abydos/3.jpeg"},
      { src: "assets/images/gallery/dendera-abydos/4.jpeg"},
      { src: "assets/images/gallery/dendera-abydos/5.jpeg"},

    ],
    itinerary: [
      { time: "05:00", title: "Early pick-up", text: "Transfer from your Marsa Alam or Hurghada hotel." },
      { time: "08:30", title: "Dendera Temple", text: "Explore the Temple of Hathor with its painted ceiling and zodiac." },
      { time: "11:00", title: "Drive to Abydos", text: "Scenic drive south to Sohag." },
      { time: "12:30", title: "Abydos Temple", text: "Visit the sacred Temple of Osiris and the List of Kings." },
      { time: "14:30", title: "Lunch", text: "Lunch at a local restaurant (included)." },
      { time: "17:00", title: "Return", text: "Transfer back to your hotel." },
    ],
    included: ["Licensed Egyptologist guide", "Entrance fees", "Lunch & drinks", "Air-conditioned transport", "Hotel pick-up & drop-off", "Bottled water"],
    excluded: ["Tips & gratuities", "Personal expenses"],
  },

  {
    id: "port-ghalib",
    name: "Port Ghalib",
    region: "Red Sea · Marsa Alam",
    icon: "ri-anchor-line",
    tagline: "A vibrant marina of colour, beauty and natural splendour",
    image: "assets/images/port-ghalib.jpg",
    rating: 4.7,
    reviews: 356,
    duration: "Half day · ~4 hrs",
    durationShort: "4 hours",
    bestFor: "Sightseeing & leisure",
    cardDesc:
      "Visit the stunning marina town of Port Ghalib — a must-see if you are staying in Marsa Alam, with its beautiful beaches, colourful promenade and natural splendour.",
    longDesc:
      "Would you like to visit Port Ghalib? If you are staying at a hotel in Marsa Alam, this is a destination you must see. Port Ghalib is an incredibly beautiful marina town that blends luxury with the natural splendour of the Red Sea coast. Stroll along the colourful promenade lined with cafes, shops and restaurants, watch the yachts in the harbour, and relax on one of the beautiful beaches with their crystal-clear waters. The town is alive with colour and beauty — from the coral reefs just offshore to the stunning desert and sea views. A visit to this incredibly beautiful beach and marina awaits you. Book now and let us show you one of the Red Sea's most charming destinations.",
    highlights: [
      { icon: "ri-anchor-line", title: "Vibrant marina & promenade" },
      { icon: "ri-store-line", title: "Cafes, shops & restaurants" },
      { icon: "ri-water-flash-line", title: "Beautiful sandy beaches" },
      { icon: "ri-ship-line", title: "Yacht harbour" },
      { icon: "ri-camera-3-line", title: "Desert-meets-sea views" },
      { icon: "ri-bubble-chart-line", title: "Coral reefs offshore" },
    ],
    gallery: [
      { src: "assets/images/gallery/port-ghalib/1.jpeg"},
      { src: "assets/images/gallery/port-ghalib/2.jpeg"},
      { src: "assets/images/gallery/port-ghalib/3.jpeg"},
      { src: "assets/images/gallery/port-ghalib/4.jpeg"},
      { src: "assets/images/gallery/port-ghalib/5.jpeg"},
      { src: "assets/images/gallery/port-ghalib/6.jpeg"},
      { src: "assets/images/gallery/port-ghalib/7.jpeg"},
      { src: "assets/images/gallery/port-ghalib/8.jpeg"},
      { src: "assets/images/gallery/port-ghalib/9.jpeg"},
      { src: "assets/images/gallery/port-ghalib/10.jpeg"},
      { src: "assets/images/gallery/port-ghalib/11.jpeg"},
      { src: "assets/images/gallery/port-ghalib/12.jpeg"},

    ],
    itinerary: [
      { time: "09:00", title: "Pick-up", text: "Transfer from your Marsa Alam hotel to Port Ghalib." },
      { time: "09:45", title: "Marina stroll", text: "Walk the colourful promenade, cafes and shops." },
      { time: "11:00", title: "Beach time", text: "Relax on the beach, swim or snorkel the offshore reefs." },
      { time: "12:30", title: "Harbour & lunch", text: "Watch the yachts and enjoy lunch by the water." },
      { time: "13:30", title: "Free time", text: "Shop, explore or simply soak in the views." },
      { time: "14:30", title: "Return", text: "Transfer back to your hotel." },
    ],
    included: ["Hotel pick-up & drop-off", "Air-conditioned transport", "Guide", "Beach access", "Bottled water"],
    excluded: ["Lunch", "Snorkelling equipment (optional)", "Tips & gratuities", "Personal expenses"],
  },
];
