/* ============================================================
   ZUZI TOURS — Tour catalogue (data layer)
   ------------------------------------------------------------
   Add a new tour = add one object to this array and it will
   automatically appear on the home grid and get its own detail
   page at  tour.html?id=<id>   — no extra HTML needed.

   NOTE: Prices/durations below are editable placeholders in EGP.
   ============================================================ */

window.ZUZI_TOURS = [
  {
    id: "luxor",
    name: "Luxor",
    region: "Upper Egypt · Nile",
    icon: "ri-ancient-gate-line",
    tagline: "The world's greatest open-air museum",
    image: "assets/images/luxor.jpg",
    rating: 4.9,
    reviews: 1284,
    duration: "Full day · ~12 hrs",
    durationShort: "12 hours",
    price: 1800,
    priceUnit: "per person",
    bestFor: "History & archaeology",
    cardDesc:
      "Walk among the colossal columns of Karnak and descend into the royal tombs of the Valley of the Kings on the East and West Banks.",
    longDesc:
      "Once the mighty capital of ancient Thebes, Luxor holds an unmatched concentration of monuments. Our full-day tour crosses both banks of the Nile — from the towering hypostyle hall of Karnak to the painted tombs hidden deep in the Valley of the Kings. A licensed Egyptologist guide brings every hieroglyph to life, while comfortable transport and a riverside lunch keep the day effortless.",
    highlights: [
      { icon: "ri-ancient-gate-line", title: "Karnak Temple Complex" },
      { icon: "ri-building-2-line", title: "Luxor Temple by night" },
      { icon: "ri-treasure-map-line", title: "Valley of the Kings" },
      { icon: "ri-flower-line", title: "Temple of Hatshepsut" },
      { icon: "ri-statue-line", title: "Colossi of Memnon" },
      { icon: "ri-ship-line", title: "Nile felucca sail" },
    ],
    gallery: [
      { src: "assets/images/gallery/luxor/1.webp", caption: "Temple of Hatshepsut on the West Bank" },
      { src: "assets/images/gallery/luxor/2.jpg", caption: "Obelisk of Hatshepsut at Karnak" },
      { src: "assets/images/gallery/luxor/3.jpg", caption: "The great hypostyle hall of Karnak" },
      { src: "assets/images/gallery/luxor/4.jpg", caption: "Approaching the Valley of the Kings" },
    ],
    itinerary: [
      { time: "05:30", title: "Pick-up & departure", text: "Air-conditioned transfer from your hotel, with breakfast on the go." },
      { time: "09:00", title: "Karnak Temple", text: "Explore the largest religious complex ever built with your guide." },
      { time: "12:00", title: "Lunch on the Nile", text: "Local restaurant overlooking the river (included)." },
      { time: "13:30", title: "Valley of the Kings", text: "Visit three royal tombs in the Valley, incl. Hatshepsut Temple." },
      { time: "17:00", title: "Colossi of Memnon", text: "Photo stop at the giant statues of Amenhotep III." },
      { time: "19:30", title: "Return", text: "Drop-off back at your hotel." },
    ],
    included: ["Licensed Egyptologist guide", "All entrance fees", "Lunch at a Nile-side restaurant", "Hotel pick-up & drop-off", "Air-conditioned transport", "Bottled water"],
    excluded: ["Tips & gratuities", "Tutankhamun's tomb (optional extra)", "Personal expenses"],
  },

  {
    id: "aswan",
    name: "Aswan",
    region: "Upper Egypt · Nubia",
    icon: "ri-ship-line",
    tagline: "Where the Nile is at its most beautiful",
    image: "assets/images/aswan.jpg",
    rating: 4.8,
    reviews: 642,
    duration: "Full day · ~10 hrs",
    durationShort: "10 hours",
    price: 1500,
    priceUnit: "per person",
    bestFor: "Culture & relaxation",
    cardDesc:
      "Sail to the temple island of Philae, stand beneath the mighty High Dam and glide over the Nile on a traditional felucca.",
    longDesc:
      "Aswan is calmer and greener than anywhere else on the Nile — a sun-drenched Nubian city of islands, granite boulders and sailboats. This tour pairs the iconic Philae Temple (rescued from the rising waters) with the engineering marvel of the High Dam, the ancient Unfinished Obelisk and a peaceful felucca cruise around Elephantine and the Botanical Garden.",
    highlights: [
      { icon: "ri-flower-line", title: "Philae Temple (Isis)" },
      { icon: "ri-building-line", title: "Aswan High Dam" },
      { icon: "ri-tools-line", title: "The Unfinished Obelisk" },
      { icon: "ri-leaf-line", title: "Botanical Garden island" },
      { icon: "ri-ship-line", title: "Traditional felucca sail" },
      { icon: "ri-store-2-line", title: "Nubian village visit" },
    ],
    gallery: [
      { src: "assets/images/gallery/aswan/1.webp", caption: "Philae Temple on its island" },
      { src: "assets/images/gallery/aswan/2.jpg", caption: "Boarding a traditional felucca" },
      { src: "assets/images/gallery/aswan/3.jpg", caption: "A peaceful felucca sail on the Nile" },
      { src: "assets/images/gallery/aswan/4.jpg", caption: "Boats drifting on the Nile at Aswan" },
    ],
    itinerary: [
      { time: "07:00", title: "Pick-up", text: "Meet your guide and head to the first site." },
      { time: "08:30", title: "Philae Temple", text: "Motorboat ride to the island temple of Isis." },
      { time: "11:00", title: "High Dam & Obelisk", text: "Visit the dam and the ancient granite quarries." },
      { time: "13:00", title: "Lunch", text: "Nubian-style lunch by the river (included)." },
      { time: "14:30", title: "Felucca cruise", text: "Relaxing sail past Elephantine & the Botanical Garden." },
      { time: "17:00", title: "Return", text: "Transfer back to your accommodation." },
    ],
    included: ["Licensed Egyptologist guide", "Entrance fees", "Motorboat to Philae", "Felucca cruise", "Lunch", "Hotel transfers", "Bottled water"],
    excluded: ["Tips & gratuities", "Optional Nubian village dinner", "Personal expenses"],
  },

  {
    id: "abu-simbel",
    name: "Abu Simbel",
    region: "Upper Egypt · Lake Nasser",
    icon: "ri-statue-line",
    tagline: "The twin temples of Ramses the Great",
    image: "assets/images/abu-simbel.jpg",
    rating: 4.9,
    reviews: 511,
    duration: "Full day · ~9 hrs",
    durationShort: "9 hours",
    price: 2200,
    priceUnit: "per person",
    bestFor: "Bucket-list monuments",
    cardDesc:
      "Stand before the four colossal statues of Ramses II and the temple of Queen Nefertari, saved stone-by-stone from the rising Nile.",
    longDesc:
      "Carved directly into the mountainside in the 13th century BC, the temples of Abu Simbel are among Egypt's most breathtaking sights — and a UNESCO World Heritage marvel. Relocated in a heroic rescue operation in the 1960s, they now rise above the waters of Lake Nasser. Your guide reveals the solar alignment, the battle reliefs and the love story behind the smaller temple dedicated to Nefertari.",
    highlights: [
      { icon: "ri-statue-line", title: "Four Colossi of Ramses II" },
      { icon: "ri-sun-line", title: "Solar alignment phenomenon" },
      { icon: "ri-heart-3-line", title: "Temple of Nefertari" },
      { icon: "ri-water-flash-line", title: "Lake Nasser views" },
      { icon: "ri-shield-star-line", title: "UNESCO rescue story" },
      { icon: "ri-ancient-pavilion-line", title: "Battle of Kadesh reliefs" },
    ],
    gallery: [
      { src: "assets/images/gallery/abu-simbel/1.jpg", caption: "Aerial view of the temple complex" },
      { src: "assets/images/gallery/abu-simbel/2.webp", caption: "The colossi at sunset over Lake Nasser" },
      { src: "assets/images/gallery/abu-simbel/3.jpg", caption: "Cruising toward Abu Simbel on Lake Nasser" },
      { src: "assets/images/gallery/abu-simbel/4.webp", caption: "Detail of the Temple of Nefertari" },
    ],
    itinerary: [
      { time: "04:30", title: "Early departure", text: "Road transfer across the desert (convoy safety) — or optional flight." },
      { time: "08:00", title: "Great Temple", text: "Guided tour of the temple of Ramses II." },
      { time: "10:00", title: "Temple of Nefertari", text: "Visit the smaller temple dedicated to Hathor & the Queen." },
      { time: "11:30", title: "Lake Nasser & free time", text: "Photo stops and the visitor centre rescue exhibit." },
      { time: "13:00", title: "Lunch", text: "Lunch in Abu Simbel (included)." },
      { time: "14:30", title: "Return", text: "Transfer back to Aswan / hotel." },
    ],
    included: ["Licensed Egyptologist guide", "Entrance fees", "Road transport in convoy", "Lunch", "Hotel pick-up & drop-off", "Bottled water"],
    excluded: ["Tips & gratuities", "Optional return flight", "Sound & light show (optional)", "Personal expenses"],
  },

  {
    id: "giza",
    name: "Giza Pyramids",
    region: "Greater Cairo",
    icon: "ri-ancient-pyramid-line",
    tagline: "The last surviving wonder of the ancient world",
    image: "assets/images/giza.jpg",
    rating: 5.0,
    reviews: 2317,
    duration: "Half day · ~5 hrs",
    durationShort: "5 hours",
    price: 1200,
    priceUnit: "per person",
    bestFor: "First-time visitors",
    cardDesc:
      "Meet the Great Pyramid of Khufu, ride between the pyramids and unlock the mystery of the Great Sphinx on the Giza Plateau.",
    longDesc:
      "No trip to Egypt is complete without standing at the foot of the Great Pyramids of Giza — the only Ancient Wonder still standing. This half-day experience covers the full plateau: the Great Pyramid of Khufu, the pyramids of Khafre and Menkaure, a panoramic viewpoint perfect for photos, and the enigmatic Great Sphinx with its valley temple. Optional add-ons let you step inside a pyramid or visit the Grand Egyptian Museum.",
    highlights: [
      { icon: "ri-ancient-pyramid-line", title: "Great Pyramid of Khufu" },
      { icon: "ri-camera-3-line", title: "Panoramic photo point" },
      { icon: "ri-emotion-line", title: "The Great Sphinx" },
      { icon: "ri-museum-line", title: "Valley Temple" },
      { icon: "ri-horse-line", title: "Optional camel ride" },
      { icon: "ri-building-4-line", title: "Grand Egyptian Museum add-on" },
    ],
    gallery: [
      { src: "assets/images/gallery/giza/1.jpg", caption: "Camel ride across the Giza Plateau" },
      { src: "assets/images/gallery/giza/2.jpg", caption: "Riding between the pyramids" },
      { src: "assets/images/gallery/giza/3.jpg", caption: "Standing beside the Great Pyramid" },
      { src: "assets/images/gallery/giza/4.jpg", caption: "The Great Sphinx and the pyramids" },
    ],
    itinerary: [
      { time: "08:00", title: "Pick-up", text: "Transfer from your Cairo/Giza hotel." },
      { time: "09:00", title: "Great Pyramid", text: "Walk the plateau and learn about Khufu's masterpiece." },
      { time: "11:00", title: "Panoramic view", text: "Best photo spot of all three pyramids together." },
      { time: "12:00", title: "Great Sphinx", text: "Visit the Sphinx and its valley temple." },
      { time: "13:00", title: "Return", text: "Drop-off, or add the Grand Egyptian Museum." },
    ],
    included: ["Licensed Egyptologist guide", "Plateau entrance fees", "Hotel pick-up & drop-off", "Air-conditioned transport", "Bottled water"],
    excluded: ["Inside-pyramid ticket (optional)", "Camel ride (optional)", "Grand Egyptian Museum (optional)", "Tips & gratuities", "Lunch"],
  },

  {
    id: "marsa-alam",
    name: "Marsa Alam",
    region: "Red Sea · Egypt",
    icon: "ri-ship-2-line",
    tagline: "Pristine reefs, dolphins and desert nights",
    image: "assets/images/marsa-alam.webp",
    rating: 4.8,
    reviews: 876,
    duration: "Full day · ~8 hrs",
    durationShort: "8 hours",
    price: 1000,
    priceUnit: "per person",
    bestFor: "Snorkelling & diving",
    cardDesc:
      "Swim with spinner dolphins at the famous Dolphin House, snorkel virgin reefs and end the day with a Bedouin dinner under the stars.",
    longDesc:
      "Marsa Alam is the Red Sea at its most unspoiled — warm turquoise water, vibrant house reefs and the legendary Sataya Dolphin House. Our day blends a boat trip to snorkel and dive among friendly spinner dolphins with the option of a quad-bike desert safari and a traditional Bedouin dinner beneath a sky full of stars. Perfect for couples, families and ocean lovers of every level.",
    highlights: [
      { icon: "ri-emotion-happy-line", title: "Dolphin House (Sataya)" },
      { icon: "ri-water-flash-line", title: "Pristine coral reefs" },
      { icon: "ri-bubble-chart-line", title: "Snorkel & dive stops" },
      { icon: "ri-restaurant-line", title: "Bedouin dinner" },
      { icon: "ri-roadster-line", title: "Quad-bike desert safari" },
      { icon: "ri-star-smile-line", title: "Stargazing in the dunes" },
    ],
    gallery: [
      { src: "assets/images/gallery/marsa-alam/1.webp", caption: "Spinner dolphins at Sataya Reef" },
      { src: "assets/images/gallery/marsa-alam/2.webp", caption: "Swimming alongside wild dolphins" },
      { src: "assets/images/gallery/marsa-alam/3.webp", caption: "Snorkel boat over the coral gardens" },
      { src: "assets/images/gallery/marsa-alam/4.webp", caption: "An overnight trip under the stars" },
    ],
    itinerary: [
      { time: "08:00", title: "Boat departure", text: "Board at the marina and cruise toward Sataya Reef." },
      { time: "10:00", title: "Dolphin House", text: "Snorkel alongside wild spinner dolphins (2 stops)." },
      { time: "13:00", title: "Onboard lunch", text: "Fresh lunch served on the boat (included)." },
      { time: "15:00", title: "Third reef stop", text: "One more snorkel/dive over the coral gardens." },
      { time: "17:00", title: "Desert option", text: "Optional quad safari, camel ride & Bedouin dinner." },
      { time: "20:30", title: "Return", text: "Transfer back to your hotel." },
    ],
    included: ["Boat trip & crew", "Snorkelling equipment", "Two guided reef stops", "Onboard lunch & drinks", "Hotel transfers", "Guide"],
    excluded: ["Diving (optional extra)", "Quad-bike safari (optional)", "Bedouin dinner (optional)", "Tips & gratuities"],
  },

  {
    id: "hurghada",
    name: "Hurghada",
    region: "Red Sea · Egypt",
    icon: "ri-sun-line",
    tagline: "Sun, coral islands and Red Sea adventures",
    image: "assets/images/hurghada.jpg",
    rating: 4.7,
    reviews: 1503,
    duration: "Full day · ~7 hrs",
    durationShort: "7 hours",
    price: 900,
    priceUnit: "per person",
    bestFor: "Families & beach fun",
    cardDesc:
      "Cruise to the protected island of Giftun, snorkel crystal lagoons and explore the colourful reefs of the Red Sea Riviera.",
    longDesc:
      "Hurghada is the lively heart of the Red Sea Riviera, and this tour is its greatest hits. Sail to Giftun Island for white-sand beaches and protected lagoons, snorkel above teeming coral gardens, and choose from optional add-ons like a semi-submarine reef tour, parasailing or a lively evening at the Marina. A relaxed, family-friendly day on the water with everything handled.",
    highlights: [
      { icon: "ri-island-line", title: "Giftun Island" },
      { icon: "ri-water-flash-line", title: "Coral lagoon snorkelling" },
      { icon: "ri-ship-line", title: "Reef cruise" },
      { icon: "ri-restaurant-line", title: "Onboard lunch" },
      { icon: "ri-water-flash-line", title: "Semi-submarine add-on" },
      { icon: "ri-anchor-line", title: "Hurghada Marina" },
    ],
    gallery: [
      { src: "assets/images/gallery/hurghada/1.jpg", caption: "Orange Bay on Giftun Island" },
      { src: "assets/images/gallery/hurghada/2.jpg", caption: "Giftun Island National Park" },
      { src: "assets/images/gallery/hurghada/3.jpg", caption: "Snorkelling at Orange Bay" },
      { src: "assets/images/gallery/hurghada/4.jpg", caption: "Reef snorkelling on the trip" },
    ],
    itinerary: [
      { time: "08:30", title: "Boarding", text: "Pick-up and departure from the Hurghada marina." },
      { time: "10:00", title: "First reef", text: "Snorkel stop over the coral gardens." },
      { time: "12:00", title: "Giftun Island", text: "Free time on the beach & lagoon swimming." },
      { time: "13:30", title: "Onboard lunch", text: "Buffet lunch served on the boat (included)." },
      { time: "15:00", title: "Second reef", text: "Final snorkel stop before heading back." },
      { time: "16:30", title: "Return", text: "Transfer back to your hotel." },
    ],
    included: ["Boat trip & crew", "Snorkelling equipment", "Giftun Island fees", "Onboard lunch & soft drinks", "Hotel transfers", "Guide"],
    excluded: ["National park fee", "Semi-submarine (optional)", "Parasailing (optional)", "Tips & gratuities"],
  },
];
